### PR TITLE
Added CODE_OF_CONDUCT.md

### LINKED ISSUE #14: Missing Code of Conduct File in Repository
Currently, the repository lacks a Code of Conduct file, which is an essential component for fostering a healthy and inclusive open-source community. A Code of Conduct serves as a guideline for expected behaviour, ensuring that contributors and participants feel safe, respected, and valued within our community space.

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #14

### CODE REVIEW

**Comment by govind-kumarr** [comment]
Thanks @suhanipaliwal

**Comment by suhanipaliwal** [comment]
Please assign me this pull request and add the labels of gssoc and level1 on this pr as per gssoc guidelines.

**Comment by suhanipaliwal** [comment]
Please assign me this pull request and add the labels of gssoc and level1 on this pull request as per gssoc guidelines.

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and level1 on this pull request as per gssoc guidelines.

**Pull request merged**
